upstream backend_blue {
    server app-back-blue:3000;
}

upstream backend_green {
    server app-back-green:3000;
}

upstream frontend_blue {
    server app-front-blue:80;
}

upstream frontend_green {
    server app-front-green:80;
}

server {
    listen 80;

    # Ce fichier est modifié par la CI pour basculer entre blue et green
    # Il contient : set $active_backend "backend_blue"; set $active_frontend "frontend_blue";
    include /etc/nginx/active_color.txt;

    location /api/ {
        proxy_pass http://$active_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://$active_frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}