name: CI Docker - Blue/Green Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Hub Login
        shell: powershell
        run: docker login -u $env:DOCKERHUB_USERNAME -p $env:DOCKERHUB_TOKEN

      # Déterminer la couleur inactive (celle sur laquelle on va déployer)
      - name: Determine inactive color
        id: color
        shell: powershell
        run: |
          $content = Get-Content ./nginx/active_color.txt -Raw
          if ($content -match "backend_blue") {
            echo "inactive=green" >> $env:GITHUB_OUTPUT
          } else {
            echo "inactive=blue" >> $env:GITHUB_OUTPUT
          }

      # Build Backend avec tag coloré
      - name: Build backend image
        shell: powershell
        run: docker build -t backend-ci ./backend

      - name: Tag & push backend (${{ steps.color.outputs.inactive }})
        shell: powershell
        run: |
          $color = "${{ steps.color.outputs.inactive }}"
          docker tag backend-ci $env:DOCKERHUB_USERNAME/cloudnative-backend-$color`:${{ github.sha }}
          docker tag backend-ci $env:DOCKERHUB_USERNAME/cloudnative-backend-$color`:latest
          docker push $env:DOCKERHUB_USERNAME/cloudnative-backend-$color`:${{ github.sha }}
          docker push $env:DOCKERHUB_USERNAME/cloudnative-backend-$color`:latest

      # Build Frontend avec tag coloré
      - name: Build frontend image
        shell: powershell
        run: docker build -t frontend-ci ./frontend

      - name: Tag & push frontend (${{ steps.color.outputs.inactive }})
        shell: powershell
        run: |
          $color = "${{ steps.color.outputs.inactive }}"
          docker tag frontend-ci $env:DOCKERHUB_USERNAME/cloudnative-frontend-$color`:${{ github.sha }}
          docker tag frontend-ci $env:DOCKERHUB_USERNAME/cloudnative-frontend-$color`:latest
          docker push $env:DOCKERHUB_USERNAME/cloudnative-frontend-$color`:${{ github.sha }}
          docker push $env:DOCKERHUB_USERNAME/cloudnative-frontend-$color`:latest

  deploy:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Blue/Green Deploy
        shell: powershell
        run: ./scripts/deploy.ps1
        env:
          GITHUB_SHA: ${{ github.sha }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}